//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Users.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Password is incorrect..
        /// </summary>
        internal static string ErrorMessageByAuthenticate {
            get {
                return ResourceManager.GetString("ErrorMessageByAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сurrent User does not exist..
        /// </summary>
        internal static string ErrorMessageByGetCurrentUser {
            get {
                return ResourceManager.GetString("ErrorMessageByGetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user exists in the system. Click LogOut before trying to LogIn ih the system with another user..
        /// </summary>
        internal static string ErrorMessageByLogIn {
            get {
                return ResourceManager.GetString("ErrorMessageByLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user does not exist in the system..
        /// </summary>
        internal static string ErrorMessageByLogOut {
            get {
                return ResourceManager.GetString("ErrorMessageByLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut from the system is completed successfully..
        /// </summary>
        internal static string MessageLogOutSuccess {
            get {
                return ResourceManager.GetString("MessageLogOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Service API.
        /// </summary>
        internal static string SwaggerEndpointName {
            get {
                return ResourceManager.GetString("SwaggerEndpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert JWT with Bearer into field..
        /// </summary>
        internal static string SwaggerSecurityDefinition {
            get {
                return ResourceManager.GetString("SwaggerSecurityDefinition", resourceCulture);
            }
        }
    }
}
