stages:
  - build

build/src/preview:
  stage: build
  except:
    - master
    - /(?i)^release\/.+$/
    - /(?i)^\d+\.\d+\.\d+(\.\d+)?(-(alpha\w*|beta\w*|rc\w*))?$/
  dependencies:
    - prepare/src
  script:
    - SonarQube.Scanner.MSBuild.exe begin /k:org.sonarqube:$Env:CI_PROJECT_NAME /n:$Env:CI_PROJECT_NAME /d:sonar.analysis.mode=preview /d:sonar.gitlab.project_id=$Env:CI_PROJECT_PATH /d:sonar.gitlab.commit_sha=$Env:CI_BUILD_REF /d:sonar.gitlab.ref_name=$Env:CI_BUILD_REF_NAME
    - .\scripts\build.src.ps1
    - SonarQube.Scanner.MSBuild.exe end
    - .\scripts\clean.analysis.results.ps1
  artifacts:
    name: build_src
    expire_in: 1 hour

build/src:
  stage: build
  only:
    - master
    - /(?i)^\d+\.\d+\.\d+(\.\d+)?(-(alpha\w*|beta\w*|rc\w*))?$/
  dependencies:
    - prepare/src
  script:
    - SonarQube.Scanner.MSBuild.exe begin /k:org.sonarqube:$Env:CI_PROJECT_NAME /n:$Env:CI_PROJECT_NAME /v:$Env:CI_COMMIT_TAG
    - .\scripts\build.src.ps1
    - SonarQube.Scanner.MSBuild.exe end
    - .\scripts\clean.analysis.results.ps1
  artifacts:
    name: build_src
    expire_in: 1 hour